feat: convert specs to TS
zeno-ml/zeno-instance-views pull request #32
Opened 2023-11-05 07:42 UTC by cabreraalex

# Description

I think this makes it easier to maintain, create views, etc.

Also swapped the validation library to the more common and supported one.

2023-11-06 09:03 UTC, Sparkier requested changes

2023-11-06 09:03 UTC, Sparkier commented on src/lib/schema.ts
> +export enum ViewTypeEnum {
Generally find it a bit weird in TS to have `Enum` and `Type` in type/enum names. We don't do this typically in Hub. Maybe rather `ViewType`, `DisplayType`, `View`, `List`, ...

2023-11-06 09:03 UTC, Sparkier commented on src/lib/views/schema.ts
> -	}
This is not modeled in the new TS spec.

2023-11-06 19:36 UTC, cabreraalex commented on README.md
> +[![Open with Zeno](https://img.shields.io/badge/%20-open_with_zeno-612593.svg?labelColor=white&logo=data:image/svg%2bxml;base64,PHN2ZyB3aWR0aD0iMzMiIGhlaWdodD0iMzMiIHZpZXdCb3g9IjAgMCAzMyAzMyIgZmlsbD0
Same as other PR -> think we will use this generally for opening zeno projects in repos, this is just an example?

2023-11-07 12:05 UTC, Sparkier approved these changes
LGTM just need to make sure going forward that we test views on both table and non-table version.

2023-11-07 15:21 UTC, merged